def get_longest_ouptput(platform, application):
    app = platform.applications[application]
    outputs = app["supported_outputs"]
    size = 0
    use = None
    for out in outputs:
        if len(out) > size:
            size = len(out)
            use = out

    return use


def generate_configuration_parameters(dsk):
    """use this to generate the parameterers for download all v2"""
    configurations = []
    for platform in dsk.platforms_v2.platform_list:
        if len(platform.platform_versions) == 0:
            supported_versions = [""]
        else:
            supported_versions = platform.platform_versions

        for compiler in platform.supported_compilers:
            for processor in platform.processors:
                for version in supported_versions:
                    for application in platform.applications.keys():
                        config = platform.get_config(debug=True)
                        config["target_processor"] = processor.uuid
                        config["target_compiler"] = compiler.uuid

                        config["float_options"] = processor.float_options.get(
                            platform.default_selections.get("float", ""), ""
                        )
                        config["application"] = application
                        config["output_options"] = get_longest_ouptput(
                            platform, application
                        )
                        config["platform.can_build_binary"] = platform.can_build_binary
                        config["selected_platform_version"] = version
                        config["platform.name"] = platform.name
                        config["processor.display_name"] = processor.display_name
                        config["compiler.name"] = compiler.name
                        config["compiler.compiler_version"] = compiler.compiler_version
                        config["processor.profiling_enabled"] = (
                            processor.profiling_enabled
                        )

                        configurations.append(config)

            if "MPLAB" in compiler.name:
                break

    return [
        (
            configurations[i]["platform.name"]
            + " "
            + configurations[i]["selected_platform_version"],
            configurations[i],
        )
        for i in range(len(configurations))
    ]


def generate_binary_only_configuration_parameters(dsk):
    """
    use this function to generate the parameters for the tf download

    """
    configurations = []
    for platform in dsk.platforms_v2.platform_list:
        if len(platform.platform_versions) == 0:
            supported_versions = [""]
        else:
            supported_versions = platform.platform_versions

        for version in supported_versions:
            for processor in platform.processors:
                for compiler in platform.supported_compilers:
                    for application in platform.applications.keys():
                        config = platform.get_config(debug=True)
                        config["target_processor"] = processor.uuid
                        config["target_compiler"] = compiler.uuid

                        config["float_options"] = processor.float_options.get(
                            platform.default_selections.get("float", ""), ""
                        )
                        config["application"] = application
                        config["output_options"] = get_longest_ouptput(
                            platform, application
                        )
                        config["platform.can_build_binary"] = platform.can_build_binary
                        config["selected_platform_version"] = version
                        config["platform.name"] = platform.name
                        config["processor.display_name"] = processor.display_name
                        config["compiler.name"] = compiler.name
                        config["compiler.compiler_version"] = compiler.compiler_version
                        config["processor.profiling_enabled"] = (
                            processor.profiling_enabled
                        )

                        if platform.can_build_binary:
                            configurations.append(config)

    return [
        (
            configurations[i]["platform.name"]
            + " "
            + configurations[i]["selected_platform_version"],
            configurations[i],
        )
        for i in range(len(configurations))
    ]


tensorflow_parameter_configuration = [
    (
        "Silicon Labs xG24 Dev Kit 10.2.1",
        {
            "target_platform": "4e75fa7a-8f67-11ec-b909-0242ac120002",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "1b2955ac-8e65-11ec-b909-0242ac120002",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
            "selected_platform_version": "10.2.1",
            "platform.can_build_binary": False,
            "platform.name": "Silicon Labs xG24 Dev Kit",
            "processor.display_name": "EFR32MG24B310F1536IM48",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "QuickLogic QuickFeather 1.10.0",
        {
            "target_platform": "a918c1f9-285e-4691-8664-9cbae4afdeb5",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "4746fe1d-6f32-4611-962b-0318ba0e5215",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
            "selected_platform_version": "1.10.0",
            "platform.can_build_binary": True,
            "platform.name": "QuickLogic QuickFeather",
            "processor.display_name": "EOS-S3 (Cortex M4)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "Silicon Labs Thunderboard Sense 2 latest",
        {
            "target_platform": "0ef89eab-0afd-4c0b-8c72-8ceb4df362d5",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "cfea1e5c-0145-42f2-9ec4-f2cd48112e07",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=softfp -mfpu=fpv4-sp-d16",
            "selected_platform_version": "latest",
            "platform.can_build_binary": False,
            "platform.name": "Silicon Labs Thunderboard Sense 2",
            "processor.display_name": "EFR32MG12 (Mighty Gecko)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "STMicroelectronics SensorTile.Box 1.0",
        {
            "target_platform": "d949e629-9cdd-4907-bd7d-5e6744b6a4ee",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial", "BLE"],
            "application": "SensiML AI MQTT-SN",
            "target_processor": "56877a93-c205-425c-82c6-49dbe6da2549",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
            "selected_platform_version": "1.0",
            "platform.can_build_binary": True,
            "platform.name": "STMicroelectronics SensorTile.Box",
            "processor.display_name": "STM32L4 (Cortex M4)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "SparkFun Thing Plus - QuickLogic EOS S3 1.10.0",
        {
            "target_platform": "442f90db-d718-4304-8540-22cf3cbacc91",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "4746fe1d-6f32-4611-962b-0318ba0e5215",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
            "selected_platform_version": "1.10.0",
            "platform.can_build_binary": True,
            "platform.name": "SparkFun Thing Plus - QuickLogic EOS S3",
            "processor.display_name": "EOS-S3 (Cortex M4)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "Windows x86_64 ",
        {
            "target_platform": "865e322e-a180-48e3-b8be-8844d08821d8",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "822581d2-8845-4692-bcac-4446d341d4a0",
            "target_compiler": "24308768-a59d-468b-b65f-cde6071ae2b2",
            "float_options": "",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "Windows x86_64",
            "processor.display_name": "x86_64",
            "compiler.name": "mingw-64",
            "compiler.compiler_version": "9.3",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "Microchip SAMD21 ML Evaluation Kit 1.1",
        {
            "target_platform": "cd8adff3-627e-4f71-8a97-0be994f978b4",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "ab1f33eb-3d23-47c0-9574-e8cf84dfe29c",
            "target_compiler": "f2fec03f-1c6e-4089-a225-c6ba2a7b0845",
            "float_options": "",
            "selected_platform_version": "1.1",
            "platform.can_build_binary": False,
            "platform.name": "Microchip SAMD21 ML Evaluation Kit",
            "processor.display_name": "ATSAMD21G18A",
            "compiler.name": "MPLAB XC32",
            "compiler.compiler_version": "4.35",
            "processor.profiling_enabled": False,
        },
    ),
    (
        "Raspberry Pi ",
        {
            "target_platform": "ef8777a0-17c4-414a-88f8-09734308bacf",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "1b8bcfbd-7a6e-4292-8ccc-bf808e7658fc",
            "target_compiler": "5fb8c1d8-66a6-46a5-b4ca-2c5b2ec7b152",
            "float_options": "-mfloat-abi=hard -mfpu=crypto-neon-fp-armv8",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "Raspberry Pi",
            "processor.display_name": "Broadcom BCM2837A0/B0 (Raspberry Pi 3/A/B/B+)",
            "compiler.name": "GNU Arm Linux (none-linux-gnueabihf)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": False,
        },
    ),
    (
        "Raspberry Pi ",
        {
            "target_platform": "ef8777a0-17c4-414a-88f8-09734308bacf",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "e3d6cdb6-3d30-4efe-9201-592d20668c58",
            "target_compiler": "5fb8c1d8-66a6-46a5-b4ca-2c5b2ec7b152",
            "float_options": "-mfloat-abi=hard -mfpu=crypto-neon-fp-armv8",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "Raspberry Pi",
            "processor.display_name": "Broadcom BCM2711 (Raspberry Pi 4)",
            "compiler.name": "GNU Arm Linux (none-linux-gnueabihf)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": False,
        },
    ),
    (
        "M5StickC PLUS ESP32-PICO Development Kit ",
        {
            "target_platform": "7b5f3d48-debe-4bba-a02e-16024989045d",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "Arduino Model Runner",
            "target_processor": "cf65817e-154f-42b1-83e0-dc70f276d945",
            "target_compiler": "ff5e8134-1e71-480b-a5e5-686e7e61e482",
            "float_options": "",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "M5StickC PLUS ESP32-PICO Development Kit",
            "processor.display_name": "ESP32",
            "compiler.name": "ESP-IDF",
            "compiler.compiler_version": "5.0",
            "processor.profiling_enabled": False,
        },
    ),
    (
        "onsemi RSL10 Sense ",
        {
            "target_platform": "ff364ed7-b7c5-47b4-93f4-fece2ed3759c",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "1745a7ea-32d0-479c-90b9-b3a6dc508135",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=soft",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "onsemi RSL10 Sense",
            "processor.display_name": "RSL10 SIP (Cortex M3)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": False,
        },
    ),
    (
        "Infineon CY8CKIT-062S2-43012 ",
        {
            "target_platform": "2ff09dae-abdb-42bf-834f-10665613e875",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "d2b8a644-d529-447b-88d8-119ac82d31a1",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "Infineon CY8CKIT-062S2-43012",
            "processor.display_name": "PSoC 62 MCU (CY8C624ABZI-S2D44, Cortex-M4)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "MPLAB XC32 ",
        {
            "target_platform": "9afc6052-69e9-48a2-914d-be56f50c1792",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "8ef4cc15-790d-411f-8901-195c39a3373f",
            "target_compiler": "f2fec03f-1c6e-4089-a225-c6ba2a7b0845",
            "float_options": "",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "MPLAB XC32",
            "processor.display_name": "PIC32MK0256GPG064",
            "compiler.name": "MPLAB XC32",
            "compiler.compiler_version": "4.35",
            "processor.profiling_enabled": False,
        },
    ),
    (
        "NXP i.MX RT10XX ",
        {
            "target_platform": "7b65b346-95a4-4103-ac7f-f4dbeae3be78",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "cc184d32-8312-43ae-9ed2-117c89d732d2",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=hard -mfpu=fpv5-sp-d16",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "NXP i.MX RT10XX",
            "processor.display_name": "NXP i.MX RT10XX",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": False,
        },
    ),
    (
        "Arduino Nano33 BLE Sense nrf52",
        {
            "target_platform": "aaf098cb-7a11-4653-b1d3-e71800610208",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "cafbed02-09b3-494e-8c07-966fe71e9727",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=softfp -mfpu=fpv4-sp-d16",
            "selected_platform_version": "nrf52",
            "platform.can_build_binary": False,
            "platform.name": "Arduino Nano33 BLE Sense",
            "processor.display_name": "NRF52840 (Cortex M4)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
    (
        "Arduino Nicla Sense ME ",
        {
            "target_platform": "c2dd2830-1271-40d7-8652-76e4b427479e",
            "test_data": "",
            "debug": True,
            "output_options": ["Serial"],
            "application": "AI Model Runner",
            "target_processor": "2af7e581-22c6-4cdf-ae2c-21a47ac780a3",
            "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
            "float_options": "-mfloat-abi=softfp -mfpu=fpv4-sp-d16",
            "selected_platform_version": "",
            "platform.can_build_binary": False,
            "platform.name": "Arduino Nicla Sense ME",
            "processor.display_name": "NRF52832 (Cortex M4)",
            "compiler.name": "GNU Arm Embedded (none-eabi)",
            "compiler.compiler_version": "10.3.1",
            "processor.profiling_enabled": True,
        },
    ),
]


all_parameter_configuration = (
    [
        (
            "QuickLogic QuickFeather 1.10.0",
            {
                "target_platform": "a918c1f9-285e-4691-8664-9cbae4afdeb5",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "4746fe1d-6f32-4611-962b-0318ba0e5215",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "1.10.0",
                "platform.can_build_binary": True,
                "platform.name": "QuickLogic QuickFeather",
                "processor.display_name": "EOS-S3 (Cortex M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "Silicon Labs Thunderboard Sense 2 latest",
            {
                "target_platform": "0ef89eab-0afd-4c0b-8c72-8ceb4df362d5",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "cfea1e5c-0145-42f2-9ec4-f2cd48112e07",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=softfp -mfpu=fpv4-sp-d16",
                "selected_platform_version": "latest",
                "platform.can_build_binary": False,
                "platform.name": "Silicon Labs Thunderboard Sense 2",
                "processor.display_name": "EFR32MG12 (Mighty Gecko)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "Microchip PIC-IoT WG Development Board 1.0",
            {
                "target_platform": "5d685c7c-eb4b-11ec-8ea0-0242ac120002",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "707ade5e-ebf3-11ec-8ea0-0242ac120002",
                "target_compiler": "a4884a3c-ebf4-11ec-8ea0-0242ac120002",
                "float_options": "",
                "selected_platform_version": "1.0",
                "platform.can_build_binary": False,
                "platform.name": "Microchip PIC-IoT WG Development Board",
                "processor.display_name": "PIC24FJ256GA705",
                "compiler.name": "MPLAB XC16",
                "compiler.compiler_version": "2.10",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Android NDK ",
            {
                "target_platform": "9b7bc186-67d2-4ca1-bddf-174734e8c183",
                "test_data": "",
                "debug": True,
                "output_options": ["Android System"],
                "application": "AI Model Runner",
                "target_processor": "1089ec6c-3569-4c64-a75c-692d3eda1ab7",
                "target_compiler": "9beaa79e-b383-411c-b6f2-f11828debf5c",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Android NDK",
                "processor.display_name": "Android/Default",
                "compiler.name": "Android NDK",
                "compiler.compiler_version": "21.0.6113669",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "STMicroelectronics SensorTile.Box 1.0",
            {
                "target_platform": "d949e629-9cdd-4907-bd7d-5e6744b6a4ee",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial", "BLE"],
                "application": "SensiML AI MQTT-SN",
                "target_processor": "56877a93-c205-425c-82c6-49dbe6da2549",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "1.0",
                "platform.can_build_binary": True,
                "platform.name": "STMicroelectronics SensorTile.Box",
                "processor.display_name": "STM32L4 (Cortex M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "SparkFun Thing Plus - QuickLogic EOS S3 1.10.0",
            {
                "target_platform": "442f90db-d718-4304-8540-22cf3cbacc91",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "4746fe1d-6f32-4611-962b-0318ba0e5215",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "1.10.0",
                "platform.can_build_binary": True,
                "platform.name": "SparkFun Thing Plus - QuickLogic EOS S3",
                "processor.display_name": "EOS-S3 (Cortex M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "Nordic Thingy",
            {
                "target_platform": "426ec1e8-251e-4081-9b76-374bcc3724ad",
                "test_data": "",
                "debug": True,
                "output_options": ["BLE", "Serial", "LED"],
                "application": "SensiML AI",
                "target_processor": "2af7e581-22c6-4cdf-ae2c-21a47ac780a3",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Nordic Thingy",
                "processor.display_name": "NRF52832 (Cortex M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "STMicroelectronics SensorTile 1.0",
            {
                "target_platform": "6ca7ad35-6fa3-4742-9a97-f27687c92099",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial", "BLE"],
                "application": "SensiML AI",
                "target_processor": "56877a93-c205-425c-82c6-49dbe6da2549",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "1.0",
                "platform.can_build_binary": True,
                "platform.name": "STMicroelectronics SensorTile",
                "processor.display_name": "STM32L4 (Cortex M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "241a03d2-3e13-4087-9d7b-07a3f96e6dff",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M4",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "241a03d2-3e13-4087-9d7b-07a3f96e6dff",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M4",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "3cc7739d-b218-4946-9366-3ab2293d42d6",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M3",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "3cc7739d-b218-4946-9366-3ab2293d42d6",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M3",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "5192eb71-8831-474e-97b3-5f0a825303cb",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M0",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "5192eb71-8831-474e-97b3-5f0a825303cb",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M0",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "530e1a45-22d3-429b-ae03-90b28040c54d",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv5-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M7",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "530e1a45-22d3-429b-ae03-90b28040c54d",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv5-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M7",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "b003c819-90cc-4ec0-9c67-1986a74e90da",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M0+",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "b003c819-90cc-4ec0-9c67-1986a74e90da",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex M0+",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "de848043-c284-4647-8364-7cc1a8582e68",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=crypto-neon-fp-armv8",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex A53",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "ARM GCC Generic ",
            {
                "target_platform": "e9f53dfa-f434-4f24-9577-839c190f74da",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "de848043-c284-4647-8364-7cc1a8582e68",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=crypto-neon-fp-armv8",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "ARM GCC Generic",
                "processor.display_name": "Cortex A53",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "x86 GCC Generic ",
            {
                "target_platform": "26eef4c2-6317-4094-8013-08503dcd4bc5",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "822581d2-8845-4692-bcac-4446d341d4a0",
                "target_compiler": "62aabe7e-4f5d-4167-a786-072e4a8dc158",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "x86 GCC Generic",
                "processor.display_name": "x86_64",
                "compiler.name": "GCC x86_64",
                "compiler.compiler_version": "9.3.0",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "Microchip AVR128DA48 Curiosity Nano Evaluation Kit 1.0",
            {
                "target_platform": "605a6e11-3adb-4044-802f-b6ec8317e839",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "8a79e44f-b121-4470-872a-142b3e0dd1e3",
                "target_compiler": "14233b4e-161d-4ff7-b90a-5a2b5509058b",
                "float_options": "",
                "selected_platform_version": "1.0",
                "platform.can_build_binary": False,
                "platform.name": "Microchip AVR128DA48 Curiosity Nano Evaluation Kit",
                "processor.display_name": "AVR128DA48",
                "compiler.name": "MPLAB XC8",
                "compiler.compiler_version": "2.45",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Windows x86_64 ",
            {
                "target_platform": "865e322e-a180-48e3-b8be-8844d08821d8",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "822581d2-8845-4692-bcac-4446d341d4a0",
                "target_compiler": "24308768-a59d-468b-b65f-cde6071ae2b2",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Windows x86_64",
                "processor.display_name": "x86_64",
                "compiler.name": "mingw-64",
                "compiler.compiler_version": "9.3",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "Microchip SAMD21 ML Evaluation Kit 1.1",
            {
                "target_platform": "cd8adff3-627e-4f71-8a97-0be994f978b4",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "ab1f33eb-3d23-47c0-9574-e8cf84dfe29c",
                "target_compiler": "f2fec03f-1c6e-4089-a225-c6ba2a7b0845",
                "float_options": "",
                "selected_platform_version": "1.1",
                "platform.can_build_binary": False,
                "platform.name": "Microchip SAMD21 ML Evaluation Kit",
                "processor.display_name": "ATSAMD21G18A",
                "compiler.name": "MPLAB XC32",
                "compiler.compiler_version": "4.35",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Raspberry Pi ",
            {
                "target_platform": "ef8777a0-17c4-414a-88f8-09734308bacf",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "1b8bcfbd-7a6e-4292-8ccc-bf808e7658fc",
                "target_compiler": "5fb8c1d8-66a6-46a5-b4ca-2c5b2ec7b152",
                "float_options": "-mfloat-abi=hard -mfpu=crypto-neon-fp-armv8",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Raspberry Pi",
                "processor.display_name": "Broadcom BCM2837A0/B0 (Raspberry Pi 3/A/B/B+)",
                "compiler.name": "GNU Arm Linux (none-linux-gnueabihf)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Raspberry Pi ",
            {
                "target_platform": "ef8777a0-17c4-414a-88f8-09734308bacf",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "e3d6cdb6-3d30-4efe-9201-592d20668c58",
                "target_compiler": "5fb8c1d8-66a6-46a5-b4ca-2c5b2ec7b152",
                "float_options": "-mfloat-abi=hard -mfpu=crypto-neon-fp-armv8",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Raspberry Pi",
                "processor.display_name": "Broadcom BCM2711 (Raspberry Pi 4)",
                "compiler.name": "GNU Arm Linux (none-linux-gnueabihf)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "M5StickC PLUS ESP32-PICO Development Kit ",
            {
                "target_platform": "7b5f3d48-debe-4bba-a02e-16024989045d",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "cf65817e-154f-42b1-83e0-dc70f276d945",
                "target_compiler": "ff5e8134-1e71-480b-a5e5-686e7e61e482",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "M5StickC PLUS ESP32-PICO Development Kit",
                "processor.display_name": "ESP32",
                "compiler.name": "ESP-IDF",
                "compiler.compiler_version": "5.0",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "onsemi RSL10 Sense ",
            {
                "target_platform": "ff364ed7-b7c5-47b4-93f4-fece2ed3759c",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "1745a7ea-32d0-479c-90b9-b3a6dc508135",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=soft",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "onsemi RSL10 Sense",
                "processor.display_name": "RSL10 SIP (Cortex M3)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Infineon CY8CKIT-062S2-43012 ",
            {
                "target_platform": "2ff09dae-abdb-42bf-834f-10665613e875",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "d2b8a644-d529-447b-88d8-119ac82d31a1",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Infineon CY8CKIT-062S2-43012",
                "processor.display_name": "PSoC 62 MCU (CY8C624ABZI-S2D44, Cortex-M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "MPLAB XC8 ",
            {
                "target_platform": "b58d28dc-f303-11ec-b939-0242ac120002",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "304a5a19-8c9d-42c5-9900-7d9c182faf6d",
                "target_compiler": "14233b4e-161d-4ff7-b90a-5a2b5509058b",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "MPLAB XC8",
                "processor.display_name": "AVR128DA28",
                "compiler.name": "MPLAB XC8",
                "compiler.compiler_version": "2.45",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "MPLAB XC16 ",
            {
                "target_platform": "7d9cf3d2-f306-11ec-b939-0242ac120002",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "0c3912c4-8b2f-4776-8cc8-626e638060b3",
                "target_compiler": "a4884a3c-ebf4-11ec-8ea0-0242ac120002",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "MPLAB XC16",
                "processor.display_name": "dsPIC33CH128MP202",
                "compiler.name": "MPLAB XC16",
                "compiler.compiler_version": "2.10",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Espressif ESP-IDF ",
            {
                "target_platform": "6409f946-09c8-4a81-958c-cf0aaa19f694",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "cf65817e-154f-42b1-83e0-dc70f276d945",
                "target_compiler": "ff5e8134-1e71-480b-a5e5-686e7e61e482",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Espressif ESP-IDF",
                "processor.display_name": "ESP32",
                "compiler.name": "ESP-IDF",
                "compiler.compiler_version": "5.0",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Espressif ESP-IDF ",
            {
                "target_platform": "6409f946-09c8-4a81-958c-cf0aaa19f694",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "Arduino Model Runner",
                "target_processor": "cf65817e-154f-42b1-83e0-dc70f276d945",
                "target_compiler": "ff5e8134-1e71-480b-a5e5-686e7e61e482",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Espressif ESP-IDF",
                "processor.display_name": "ESP32",
                "compiler.name": "ESP-IDF",
                "compiler.compiler_version": "5.0",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "NXP i.MX RT10XX ",
            {
                "target_platform": "7b65b346-95a4-4103-ac7f-f4dbeae3be78",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "cc184d32-8312-43ae-9ed2-117c89d732d2",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv5-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "NXP i.MX RT10XX",
                "processor.display_name": "NXP i.MX RT10XX",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": False,
            },
        ),
        (
            "Arduino Nano33 BLE Sense nrf52",
            {
                "target_platform": "aaf098cb-7a11-4653-b1d3-e71800610208",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "cafbed02-09b3-494e-8c07-966fe71e9727",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=softfp -mfpu=fpv4-sp-d16",
                "selected_platform_version": "nrf52",
                "platform.can_build_binary": False,
                "platform.name": "Arduino Nano33 BLE Sense",
                "processor.display_name": "NRF52840 (Cortex M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "Arduino Nicla Sense ME ",
            {
                "target_platform": "c2dd2830-1271-40d7-8652-76e4b427479e",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "2af7e581-22c6-4cdf-ae2c-21a47ac780a3",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=softfp -mfpu=fpv4-sp-d16",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "Arduino Nicla Sense ME",
                "processor.display_name": "NRF52832 (Cortex M4)",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "Silicon Labs xG24 Dev Kit 10.2.1",
            {
                "target_platform": "4e75fa7a-8f67-11ec-b909-0242ac120002",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "1b2955ac-8e65-11ec-b909-0242ac120002",
                "target_compiler": "2e8bdcf0-557a-41bd-a41d-64e443ec97a9",
                "float_options": "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
                "selected_platform_version": "10.2.1",
                "platform.can_build_binary": False,
                "platform.name": "Silicon Labs xG24 Dev Kit",
                "processor.display_name": "EFR32MG24B310F1536IM48",
                "compiler.name": "GNU Arm Embedded (none-eabi)",
                "compiler.compiler_version": "10.3.1",
                "processor.profiling_enabled": True,
            },
        ),
        (
            "MPLAB XC32 ",
            {
                "target_platform": "9afc6052-69e9-48a2-914d-be56f50c1792",
                "test_data": "",
                "debug": True,
                "output_options": ["Serial"],
                "application": "AI Model Runner",
                "target_processor": "8ef4cc15-790d-411f-8901-195c39a3373f",
                "target_compiler": "f2fec03f-1c6e-4089-a225-c6ba2a7b0845",
                "float_options": "",
                "selected_platform_version": "",
                "platform.can_build_binary": False,
                "platform.name": "MPLAB XC32",
                "processor.display_name": "PIC32MK0256GPG064",
                "compiler.name": "MPLAB XC32",
                "compiler.compiler_version": "4.35",
                "processor.profiling_enabled": False,
            },
        ),
    ],
)
