# Generated by Django 3.2.12 on 2024-11-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamanager", "0086_label_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lock_schema",
            field=models.BooleanField(default=False),
        ),
    ]
